version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-orderservice
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderservice-product
    ports:
      - "3308:3306"
    volumes:
      - /Users/joaof/Documents/volumes/mysql